### ISSUE TITLE
[Feature request] Additional parameters for adding noise

### ISSUE THREAD

**Issue by miasik** [Haoming02/sd-webui-resharpen#1]
First steps for initial rendering and latent hires fix are really sensitive for noise injection.
Lasts steps could be left "sane" to make some "housecleaning"
Could you please add parameters such as "start step" and "stop step" separately for initial and hires.fix?

Their behavior might be the next:
if value is floating (0.5 as an example) it means that its real value is 0.5*NumberOfSteps
if value is integer (2 as an example) it meaning is literal, so 2 steps

**Comment by Haoming02** [comment]
*(using the same logics as Vectorscope-CC)*

**Comment by miasik** [comment]
> _(using the same logics as Vectorscope-CC)_
Much, much better now!
But it's not completed ;-)
In my logic and experience I'd like to use different scaling for the first and hires steps — cos and sin respectively.
Please make separate settings for the steps

**Comment by Haoming02** [comment]
Now `scaling` is separated for normal `txt2img` and `Hires. fix`

<p align="center"><img src="https://github.com/Haoming02/sd-webui-resharpen/assets/73768377/4239c879-a5bb-4c02-b2fe-b6b9a4e7164f"></p>

**Comment by miasik** [comment]
> Now `scaling` is separated for normal `txt2img` and `Hires. fix`

Super! Could you please elaborate on functions to scale? As we can see there:
https://s3-us-west-2.amazonaws.com/courses-images/wp-content/uploads/sites/3252/2018/07/19143101/CNX_Precalc_Figure_06_01_005.jpg
The functions have one period from 0 to 2pi. Do you use the full period or partially?

**Comment by Haoming02** [comment]
You can refer to [res_scaling.py](https://github.com/Haoming02/sd-webui-resharpen/blob/main/scripts/res_scaling.py)

~~If my math didn't fail me~~, it only goes from 0° to 90° 

**ie.** `1.0` to `0.0` for `cos`; `0.0` to `1.0` for `sin`

**Comment by miasik** [comment]
> ~If my math didn't fail me~, it only goes from 0° to 90°
> **ie.** `1.0` to `0.0` for `cos`; `0.0` to `1.0` for `sin`

Thanks. it's clear now!
Need more time to check if I can work without start and stop steps limits
