### ISSUE TITLE
Resharpen seems to stop batching

### ISSUE THREAD

**Issue by jarmstrong43** [Haoming02/sd-webui-resharpen#2]
When I increase my batch count from 1 in txt2img when enabling resharpen I get "HINT: We don't support broadcasting, please use `expand` yourself before calling `memory_efficient_attention`".  I only seem to get this with this extension enabled.
Tell a lie something else is causing this maybe just coincidence it was when I installed Resharpen.

**Comment by jarmstrong43** [comment]
see above

**Comment by Haoming02** [comment]
Sorry, but I have 0 idea on how to fix that...

**Comment by Haoming02** [comment]
Doesn't seem to happen on Forge however
