### ISSUE TITLE
Path Error in resharpen.py with StableDiffusionWebUI Forge – Suggestion for __init__.py Placement

### ISSUE THREAD

**Issue by fumitakayano** [Haoming02/sd-webui-resharpen#3]
Dear Haoming02,

Thank you for creating the "sharpness" control extension for StableDiffusionWebUI. I tried using this extension with StableDiffusionWebUI Forge and encountered a path error in resharpen.py.

I was wondering if placing the __init__.py file in the specified locations might resolve the error, reducing the likelihood of others encountering the same issue. The specified locations are sd-webui-resharpen and scripts.

Your consideration would be greatly appreciated. Thank you in advance.

**Comment by Haoming02** [comment]
ReSharpen does work in Forge for me

And no, Automatic1111 and Forge extensions do not need `__init__.py` files
