### ISSUE TITLE
Use via API?

### ISSUE THREAD

**Issue by MotherSoraka** [Haoming02/sd-webui-resharpen#7]
Hi,
First, This is one of absolute best extensions i've discovered so far!
Congratulation on achieving this.

Now, is it possible to use this extension via the API or is it only usable through the WebUi?

**Comment by Haoming02** [comment]
Should work with API just fine.

It takes 3 variable: 
- **enable:** `bool`
- **sharpness:** `float`
- **hr. sharpness:** `float`

```json
"resharpen": {
    "args": [
        true,
        1.0,
        0.0
    ]
}
```
