### ISSUE TITLE
Error: AttributeError: 'KDiffusionSampler' object has no attribute 'trajectory_enable'

### ISSUE THREAD

**Issue by Volnovik** [Haoming02/sd-webui-resharpen#9]
Getting error after clicking Generate in SDWebUI:
AttributeError: 'KDiffusionSampler' object has no attribute 'trajectory_enable'

Steps to recreate:
Load SDWebUI.
**Disable** ReSharpen
Error is present.

Error is absent if ReSharpen is enabled.
After first successful generation you can disable it.
Deleting extension fixes issue.
I am not the only one with the issue, see last replies here:
[https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15588](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15588)

SDWebUI Version: v1.9.4
Windows
Installed extensions:
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git 
sd-webui-cd-tuner | https://github.com/hako-mikan/sd-webui-cd-tuner.git
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git 
sd-webui-freeu | https://github.com/ljleb/sd-webui-freeu
sd-webui-incantations | https://github.com/v0xie/sd-webui-incantations.git
sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing.git 
sd-webui-inpaint-anything | https://github.com/Uminosachi/sd-webui-inpaint-anything.git 
sd-webui-kohya-hiresfix | https://github.com/wcde/sd-webui-kohya-hiresfix.git 
sd-webui-lama-cleaner-masked-content | https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content.git 
sd-webui-mosaic-outpaint | https://github.com/Haoming02/sd-webui-mosaic-outpaint.git 
sd-webui-resharpen | https://github.com/Haoming02/sd-webui-resharpen.git 
sd-webui-segment-anything | https://github.com/continue-revolution/sd-webui-segment-anything.git 
sd-webui-tabs-extension | https://github.com/Haoming02/sd-webui-tabs-extension.git 
sd-webui-yandere-inpaint-masked-content | https://github.com/light-and-ray/sd-webui-yandere-inpaint-masked-content.git 
sd_civitai_extension | https://github.com/civitai/sd_civitai_extension 
stable-diffusion-webui-dataset-tag-editor | https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git
webui-fooocus-prompt-expansion | https://github.com/power88/webui-fooocus-prompt-expansion.git

**Comment by ostap667inbox** [comment]
Both A1111 and Forge broken now when Resharpen installed (even if it is not turned on)

**Comment by Volnovik** [comment]
Small update
Hires fix is also broken if Hires. Fix Sharpness in not zero.

**Comment by Haoming02** [comment]
Should be fixed now

**Comment by Volnovik** [comment]
I confirm, it is fixed for me
